import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, CircleDashed, ClipboardList, PencilLine, RefreshCw, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fetchJudgeAssignmentPage, loadReference, subscribeToResults, type JudgeAssignmentPageRow, type Reference } from '@/lib/api';
import type { JudgeAssignmentStatus } from '@/lib/judgeAssignments';
import { errorMessage } from '@/lib/supabase';
import Pagination from '@/components/Pagination';
import { Alert, Badge, Button, Card, EmptyState, Input, OrgBadge, PageHeader, Select, Spinner, StatCard } from '@/components/ui';

const rowStatus = (row: JudgeAssignmentPageRow): JudgeAssignmentStatus => !row.evaluation_id ? 'not_started' : row.evaluation_status === 'submitted' ? 'submitted' : 'in_progress';
const action = (status: JudgeAssignmentStatus) => status === 'submitted' ? 'View Submission' : status === 'in_progress' ? 'Continue Evaluation' : 'Start Evaluation';
function Status({ status }: { status: JudgeAssignmentStatus }) { return status === 'submitted' ? <Badge tone="green"><CheckCircle2 size={12}/>Submitted</Badge> : status === 'in_progress' ? <Badge tone="amber"><PencilLine size={12}/>In Progress</Badge> : <Badge><CircleDashed size={12}/>Not Started</Badge>; }

export default function AssignedTeamsPage() {
  const [reference,setReference]=useState<Reference|null>(null),[rows,setRows]=useState<JudgeAssignmentPageRow[]>([]),[error,setError]=useState<string|null>(null);
  const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  const [query,setQuery]=useState(''),[organization,setOrganization]=useState(''),[level,setLevel]=useState(''),[governorate,setGovernorate]=useState(''),[status,setStatus]=useState<JudgeAssignmentStatus|''>('');
  const [counts,setCounts]=useState({not_started:0,in_progress:0,submitted:0,total:0});
  const filters={search:query,organization,level,governorate,status};
  const load=useCallback(async(quiet=false)=>{quiet?setRefreshing(true):setLoading(true);try{const [ref,current,all,notStarted,inProgress,submitted]=await Promise.all([loadReference(true),fetchJudgeAssignmentPage(filters,page,pageSize),fetchJudgeAssignmentPage({},1,20),fetchJudgeAssignmentPage({status:'not_started'},1,20),fetchJudgeAssignmentPage({status:'in_progress'},1,20),fetchJudgeAssignmentPage({status:'submitted'},1,20)]);setReference(ref);setRows(current.rows);setTotal(current.total);setCounts({total:all.total,not_started:notStarted.total,in_progress:inProgress.total,submitted:submitted.total});setError(null);}catch(e){setError(errorMessage(e));}finally{setLoading(false);setRefreshing(false)}},[query,organization,level,governorate,status,page,pageSize]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),query?250:0);return()=>window.clearTimeout(timer)},[load,query]);
  useEffect(()=>{const unsub=subscribeToResults(()=>void load(true));return unsub},[load]);
  const change=(setter:(value:string)=>void,value:string)=>{setter(value);setPage(1)};
  if(loading&&!reference)return <Spinner label="Loading assigned teams…"/>;
  if(!reference)return <Alert tone="error" title="Could not load assignments">{error}</Alert>;
  return <div><PageHeader title="Assigned Teams" subtitle="Track every team assigned to you and continue each evaluation from its current status." actions={<Button variant="secondary" loading={refreshing} onClick={()=>void load(true)}><RefreshCw size={16}/>Refresh</Button>}/>{error&&<Alert tone="error" className="mb-4">{error}</Alert>}
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Assigned" value={counts.total} icon={<ClipboardList size={20}/>} /><StatCard label="Not Started" value={counts.not_started} icon={<CircleDashed size={20}/>} tone="slate"/><StatCard label="In Progress" value={counts.in_progress} icon={<PencilLine size={20}/>} tone="amber"/><StatCard label="Submitted" value={counts.submitted} icon={<CheckCircle2 size={20}/>} tone="green"/></div>
    <Card className="mb-4 p-3"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-6"><div className="relative md:col-span-2"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input className="pl-8" placeholder="Search Team ID, team name or project" value={query} onChange={e=>change(setQuery,e.target.value)}/></div><Select value={organization} onChange={e=>{change(setOrganization,e.target.value);setLevel('')}}><option value="">All organizations</option><option>DEMI</option><option>DECI</option></Select><Select value={level} onChange={e=>change(setLevel,e.target.value)}><option value="">All grades / levels</option>{reference.levels.filter(x=>!organization||x.organization===organization).map(x=><option key={x.code} value={x.code}>{x.organization} · {x.label}</option>)}</Select><Select value={governorate} onChange={e=>change(setGovernorate,e.target.value)}><option value="">All governorates</option>{reference.governorates.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</Select><Select value={status} onChange={e=>{setStatus(e.target.value as JudgeAssignmentStatus|'');setPage(1)}}><option value="">Any status</option><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="submitted">Submitted</option></Select></div></Card>
    <Card className="overflow-hidden">{rows.length===0?<EmptyState icon={<ClipboardList/>} title={total?'No teams on this page':'No assigned teams match'}/>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase text-slate-500"><th className="px-5 py-3">Team ID</th><th className="px-3 py-3">Team</th><th className="px-3 py-3">Project</th><th className="px-3 py-3">Organization</th><th className="px-3 py-3">Grade / level</th><th className="px-3 py-3">Governorate</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{rows.map(row=>{const s=rowStatus(row);return <tr key={row.id}><td className="px-5 py-3 font-semibold">{row.team_code}</td><td className="px-3 py-3">{row.name}</td><td className="px-3 py-3">{row.project_name}</td><td className="px-3 py-3"><OrgBadge org={row.organization}/></td><td className="px-3 py-3">{row.level_label}</td><td className="px-3 py-3">{row.governorate_name}</td><td className="px-3 py-3"><Status status={s}/></td><td className="px-5 py-3 text-right"><Link className="inline-flex h-9 items-center rounded-full bg-brand-600 px-4 text-xs font-semibold text-white" to={`/evaluate/${row.id}`}>{action(s)}</Link></td></tr>})}</tbody></table></div>}<Pagination page={page} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/></Card>
  </div>;
}
