#!/usr/bin/env python3
"""Generate the reference-data migration from rubrics/rubrics.json.

This historical generator reproduces the original six-rubric migration. Grade 6
is deliberately excluded because it lives in the additive 0005 migration. Run:

    python3 scripts/gen_seed.py > supabase/migrations/20260928000004_seed_reference.sql
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "rubrics" / "rubrics.json").read_text())


def q(s) -> str:
    return "'" + str(s).replace("'", "''") + "'"


out = []
w = out.append
w("-- =============================================================================")
w("-- Reference data: governorates, competitions, levels, 1-5 scale, six rubrics")
w("-- GENERATED by scripts/gen_seed.py from rubrics/rubrics.json — do not hand-edit")
w("-- =============================================================================")
w("")
w("insert into public.governorates (code, name, sort_order) values")
govs = [("ALX", "Alexandria"), ("CAI", "Cairo"), ("MNF", "Monufia"), ("AST", "Assiut"), ("SUZ", "Suez")]
w(",\n".join(f"  ({q(c)}, {q(n)}, {i+1})" for i, (c, n) in enumerate(govs)))
w("on conflict (code) do update set name = excluded.name, sort_order = excluded.sort_order;")
w("")
w("insert into public.score_levels (value, label, description) values")
w(",\n".join(f"  ({l['value']}, {q(l['label'])}, {q(l['description'])})" for l in data["score_levels"]))
w("on conflict (value) do update set label = excluded.label, description = excluded.description;")
w("")

for t in (item for item in data["templates"] if item["id"] != "DEMI_G6"):
    w(f"-- ---- {t['title']} ({t['source_pdf']})")
    w("insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values")
    w(f"  ({q(t['id'])}, {q(t['title'])}, {q(t['subtitle'])}, {q(t['source_pdf'])}, {q(data['scale_instruction'])}, {q(data['guidance'])}, {t['core_max']}, {t['bonus_max']})")
    w("on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,")
    w("  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;")
    sec_rows, crit_rows = [], []
    for i, s in enumerate(t["sections"], 1):
        sid = f"{t['id']}.S{i}"
        sec_rows.append(f"  ({q(sid)}, {q(t['id'])}, {i}, {q(s['title'])}, {s['weight']}, false)")
        for j, (title, desc) in enumerate(s["criteria"], 1):
            crit_rows.append(f"  ({q(sid + '.C' + str(j))}, {q(sid)}, {q(t['id'])}, false, {j}, {q(title)}, {q(desc)}, 5)")
    bid = f"{t['id']}.BONUS"
    sec_rows.append(f"  ({q(bid)}, {q(t['id'])}, {len(t['sections'])+1}, {q(t['bonus']['title'])}, {t['bonus_max']}, true)")
    for j, (title, desc) in enumerate(t["bonus"]["criteria"], 1):
        crit_rows.append(f"  ({q(bid + '.C' + str(j))}, {q(bid)}, {q(t['id'])}, true, {j}, {q(title)}, {q(desc)}, 5)")
    w("insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values")
    w(",\n".join(sec_rows))
    w("on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;")
    w("insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values")
    w(",\n".join(crit_rows))
    w("on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;")
    w("")

w("insert into public.competitions (code, organization, label, template_id, sort_order) values")
comps = [("DEMI_G4", "DEMI", "Grade 4", "DEMI_G4", 1), ("DEMI_G5", "DEMI", "Grade 5", "DEMI_G5", 2),
         ("DECI_L1", "DECI", "Level 1", "DECI_L1", 3), ("DECI_L2", "DECI", "Level 2", "DECI_L2", 4),
         ("DECI_L3", "DECI", "Level 3", "DECI_L3", 5), ("DECI_L45", "DECI", "Levels 4 & 5", "DECI_L45", 6)]
w(",\n".join(f"  ({q(a)}, {q(b)}, {q(c)}, {q(d)}, {e})" for a, b, c, d, e in comps))
w("on conflict (code) do update set organization = excluded.organization, label = excluded.label, template_id = excluded.template_id, sort_order = excluded.sort_order;")
w("")
w("insert into public.levels (code, organization, label, competition_code, sort_order) values")
levels = [("G4", "DEMI", "Grade 4", "DEMI_G4", 1), ("G5", "DEMI", "Grade 5", "DEMI_G5", 2),
          ("L1", "DECI", "Level 1", "DECI_L1", 3), ("L2", "DECI", "Level 2", "DECI_L2", 4),
          ("L3", "DECI", "Level 3", "DECI_L3", 5), ("L4", "DECI", "Level 4", "DECI_L45", 6),
          ("L5", "DECI", "Level 5", "DECI_L45", 7)]
w(",\n".join(f"  ({q(a)}, {q(b)}, {q(c)}, {q(d)}, {e})" for a, b, c, d, e in levels))
w("on conflict (code) do update set organization = excluded.organization, label = excluded.label, competition_code = excluded.competition_code, sort_order = excluded.sort_order;")
w("")
w("insert into public.results_signal (competition_code) select code from public.competitions on conflict do nothing;")
w("")
w("-- Integrity check: every section weight = rows x 5, core sections sum to core_max,")
w("-- bonus section weight = bonus_max. Fails the migration if the seed is inconsistent.")
w("""do $$
declare bad text;
begin
  select string_agg(s.id, ', ') into bad
  from public.rubric_sections s
  where s.weight <> (select count(*) * 5 from public.rubric_criteria c where c.section_id = s.id);
  if bad is not null then raise exception 'Section weight mismatch: %', bad; end if;

  select string_agg(t.id, ', ') into bad
  from public.rubric_templates t
  where t.core_max <> (select coalesce(sum(weight), 0) from public.rubric_sections where template_id = t.id and not is_bonus)
     or t.bonus_max <> (select coalesce(sum(weight), 0) from public.rubric_sections where template_id = t.id and is_bonus);
  if bad is not null then raise exception 'Template total mismatch: %', bad; end if;
end;
$$;""")
print("\n".join(out))
