-- =============================================================================
-- Reference data: governorates, competitions, levels, 1-5 scale, six rubrics
-- GENERATED by scripts/gen_seed.py from rubrics/rubrics.json — do not hand-edit
-- =============================================================================

insert into public.governorates (code, name, sort_order) values
  ('ALX', 'Alexandria', 1),
  ('CAI', 'Cairo', 2),
  ('MNF', 'Monufia', 3),
  ('AST', 'Assiut', 4),
  ('SUZ', 'Suez', 5)
on conflict (code) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.score_levels (value, label, description) values
  (1, 'Weak', 'Missing, incorrect, non-functional, or little/no meaningful evidence.'),
  (2, 'Developing', 'Partially demonstrated; important gaps remain or substantial support is needed.'),
  (3, 'Meets Expectations', 'Core requirement is present, understandable, and works at an acceptable/basic level.'),
  (4, 'Strong', 'Complete, accurate, well integrated, and supported by good evidence; only minor issues.'),
  (5, 'Excellent', 'Highly effective, reliable, purposeful, well-tested/polished, and clearly justified by the team.')
on conflict (value) do update set label = excluded.label, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DEMI Grade 4 (DEMI_Grade_4_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DEMI_G4', 'Stage 3 Judges'' Rubric - DEMI Grade 4', 'App Lab Project - Stage 3 Judge Evaluation', 'DEMI_Grade_4_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 10)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DEMI_G4.S1', 'DEMI_G4', 1, 'Problem, Research & Solution', 20, false),
  ('DEMI_G4.S2', 'DEMI_G4', 2, 'UX & Prototype Design', 15, false),
  ('DEMI_G4.S3', 'DEMI_G4', 3, 'Programming & Functionality', 25, false),
  ('DEMI_G4.S4', 'DEMI_G4', 4, 'Testing & Improvement', 15, false),
  ('DEMI_G4.S5', 'DEMI_G4', 5, 'Business & Value', 10, false),
  ('DEMI_G4.S6', 'DEMI_G4', 6, 'Teamwork & Presentation', 15, false),
  ('DEMI_G4.BONUS', 'DEMI_G4', 7, 'Extra Requirements / Optional Bonus', 10, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DEMI_G4.S1.C1', 'DEMI_G4.S1', 'DEMI_G4', false, 1, 'Problem & target user', 'The team clearly defines the real-world problem, who is affected, and why it matters.', 5),
  ('DEMI_G4.S1.C2', 'DEMI_G4.S1', 'DEMI_G4', false, 2, 'Research on similar solutions', 'Shows credible examples/screenshots of 1-2 similar apps or solutions and explains what was learned.', 5),
  ('DEMI_G4.S1.C3', 'DEMI_G4.S1', 'DEMI_G4', false, 3, 'Research insight / gap', 'Explains what is missing or could be improved in existing solutions and connects that insight to the project.', 5),
  ('DEMI_G4.S1.C4', 'DEMI_G4.S1', 'DEMI_G4', false, 4, 'App solution & main features', 'The app purpose and 2-3 main features directly address the identified problem and user needs.', 5),
  ('DEMI_G4.S2.C1', 'DEMI_G4.S2', 'DEMI_G4', false, 1, 'User flow', 'Screen-to-screen journey is logical, complete, and easy to follow.', 5),
  ('DEMI_G4.S2.C2', 'DEMI_G4.S2', 'DEMI_G4', false, 2, 'Wireframes / screen design', 'Screens or mockups match the planned features and show a clear interface structure.', 5),
  ('DEMI_G4.S2.C3', 'DEMI_G4.S2', 'DEMI_G4', false, 3, 'Usability & design consistency', 'Buttons, labels, navigation, layout, and visual choices are understandable and consistent for the target user.', 5),
  ('DEMI_G4.S3.C1', 'DEMI_G4.S3', 'DEMI_G4', false, 1, 'Working prototype', 'Core app screens and planned features function during the demonstration.', 5),
  ('DEMI_G4.S3.C2', 'DEMI_G4.S3', 'DEMI_G4', false, 2, 'Events & user input', 'Events such as button clicks trigger the correct actions and user inputs are handled properly.', 5),
  ('DEMI_G4.S3.C3', 'DEMI_G4.S3', 'DEMI_G4', false, 3, 'Variables & conditions', 'Variables and conditional logic are used correctly to control app behavior.', 5),
  ('DEMI_G4.S3.C4', 'DEMI_G4.S3', 'DEMI_G4', false, 4, 'Loops / functions / data logic', 'Uses suitable loops, functions, lists, or reusable logic where needed; logic is organized rather than repeated unnecessarily.', 5),
  ('DEMI_G4.S3.C5', 'DEMI_G4.S3', 'DEMI_G4', false, 5, 'Reliability & correctness', 'App produces correct results, handles common mistakes reasonably, and does not break during normal use.', 5),
  ('DEMI_G4.S4.C1', 'DEMI_G4.S4', 'DEMI_G4', false, 1, 'Testing coverage', 'Team tests important screens, buttons, inputs, and user journeys instead of only one happy path.', 5),
  ('DEMI_G4.S4.C2', 'DEMI_G4.S4', 'DEMI_G4', false, 2, 'Evidence of testing', 'Shows concrete evidence such as test notes, screenshots, user feedback, before/after examples, or repeated trials.', 5),
  ('DEMI_G4.S4.C3', 'DEMI_G4.S4', 'DEMI_G4', false, 3, 'Improvement from findings', 'Team identifies issues found during testing and explains or demonstrates meaningful improvements.', 5),
  ('DEMI_G4.S5.C1', 'DEMI_G4.S5', 'DEMI_G4', false, 1, 'User value & delivery idea', 'Explains who benefits, what value the app provides, and a realistic way it could be offered or shared.', 5),
  ('DEMI_G4.S5.C2', 'DEMI_G4.S5', 'DEMI_G4', false, 2, 'Differentiation & feasibility', 'Explains why the solution is useful compared with alternatives and keeps the idea realistic for the intended users.', 5),
  ('DEMI_G4.S6.C1', 'DEMI_G4.S6', 'DEMI_G4', false, 1, 'Shared teamwork & roles', 'Participation is balanced; team members contribute and can explain their own role in the project.', 5),
  ('DEMI_G4.S6.C2', 'DEMI_G4.S6', 'DEMI_G4', false, 2, 'Clear communication & demo', 'Presentation is organized, understandable, within time, and the demo supports the story of the project.', 5),
  ('DEMI_G4.S6.C3', 'DEMI_G4.S6', 'DEMI_G4', false, 3, 'Questions & project understanding', 'Team members answer judge questions clearly and show shared understanding of the app, decisions, and testing.', 5),
  ('DEMI_G4.BONUS.C1', 'DEMI_G4.BONUS', 'DEMI_G4', true, 1, 'Advanced app feature - usefulness & depth', 'Optional extra feature meaningfully strengthens the same app rather than adding an unrelated idea.', 5),
  ('DEMI_G4.BONUS.C2', 'DEMI_G4.BONUS', 'DEMI_G4', true, 2, 'Advanced app feature - working evidence', 'Shows screenshots/code or a working demonstration proving the advanced feature is implemented or credibly prototyped.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DEMI Grade 5 (DEMI_Grade_5_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DEMI_G5', 'Stage 3 Judges'' Rubric - DEMI Grade 5', 'Arduino + AI Project - Stage 3 Judge Evaluation', 'DEMI_Grade_5_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 10)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DEMI_G5.S1', 'DEMI_G5', 1, 'Problem, Research & Solution', 15, false),
  ('DEMI_G5.S2', 'DEMI_G5', 2, 'Hardware & System Design', 25, false),
  ('DEMI_G5.S3', 'DEMI_G5', 3, 'Programming & AI Integration', 20, false),
  ('DEMI_G5.S4', 'DEMI_G5', 4, 'Prototype, Testing & Improvement', 15, false),
  ('DEMI_G5.S5', 'DEMI_G5', 5, 'Business & Value', 10, false),
  ('DEMI_G5.S6', 'DEMI_G5', 6, 'Teamwork & Presentation', 15, false),
  ('DEMI_G5.BONUS', 'DEMI_G5', 7, 'Extra Requirements / Optional Bonus', 10, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DEMI_G5.S1.C1', 'DEMI_G5.S1', 'DEMI_G5', false, 1, 'Problem, target user & research', 'Clearly explains the problem, user, importance, and supporting research about similar ideas or needs.', 5),
  ('DEMI_G5.S1.C2', 'DEMI_G5.S1', 'DEMI_G5', false, 2, 'Solution alignment', 'The proposed solution and its functions directly address the researched problem.', 5),
  ('DEMI_G5.S1.C3', 'DEMI_G5.S1', 'DEMI_G5', false, 3, 'User value', 'The team can explain how the final system helps the target user and why the solution is worthwhile.', 5),
  ('DEMI_G5.S2.C1', 'DEMI_G5.S2', 'DEMI_G5', false, 1, 'Purposeful kit/component choice', 'Hardware is selected because it fits the solution; unnecessary components are avoided and each chosen part has a clear role.', 5),
  ('DEMI_G5.S2.C2', 'DEMI_G5.S2', 'DEMI_G5', false, 2, 'Input/output component use', 'Sensors and outputs/actuators are used correctly and their roles match the Stage 2 hardware plan.', 5),
  ('DEMI_G5.S2.C3', 'DEMI_G5.S2', 'DEMI_G5', false, 3, 'Circuit correctness & safety', 'Connections are technically appropriate, organized, and safe for the intended prototype.', 5),
  ('DEMI_G5.S2.C4', 'DEMI_G5.S2', 'DEMI_G5', false, 4, 'System integration', 'Input -> Arduino/controller -> output behavior works as one coherent system and matches the block/circuit design.', 5),
  ('DEMI_G5.S2.C5', 'DEMI_G5.S2', 'DEMI_G5', false, 5, 'Best use of hardware & reliability', 'Hardware capabilities are used effectively for the problem, and the physical setup performs consistently during repeated demonstrations.', 5),
  ('DEMI_G5.S3.C1', 'DEMI_G5.S3', 'DEMI_G5', false, 1, 'Programming logic', 'Events/inputs, variables, conditions, loops, and outputs work together correctly.', 5),
  ('DEMI_G5.S3.C2', 'DEMI_G5.S3', 'DEMI_G5', false, 2, 'Code organization', 'Functions or reusable blocks are used appropriately; code is readable and avoids unnecessary repetition.', 5),
  ('DEMI_G5.S3.C3', 'DEMI_G5.S3', 'DEMI_G5', false, 3, 'AI/ML feature relevance', 'AI feature supports the same problem and is more than a disconnected add-on.', 5),
  ('DEMI_G5.S3.C4', 'DEMI_G5.S3', 'DEMI_G5', false, 4, 'AI evidence & integration', 'Team shows model/concept evidence and clearly explains how AI input/output connects to the overall solution.', 5),
  ('DEMI_G5.S4.C1', 'DEMI_G5.S4', 'DEMI_G5', false, 1, 'Prototype completeness', 'The physical/digital prototype demonstrates the main planned behavior end-to-end.', 5),
  ('DEMI_G5.S4.C2', 'DEMI_G5.S4', 'DEMI_G5', false, 2, 'Evidence of testing', 'Shows repeated tests, observations, measurements, screenshots, logs, or other evidence rather than only stating that testing happened.', 5),
  ('DEMI_G5.S4.C3', 'DEMI_G5.S4', 'DEMI_G5', false, 3, 'Improvement & reliability', 'Team uses test findings to improve timing, thresholds, interaction, accuracy, or reliability and can explain the change.', 5),
  ('DEMI_G5.S5.C1', 'DEMI_G5.S5', 'DEMI_G5', false, 1, 'Customer & value proposition', 'Target customer/user matches the original problem and the value is clear.', 5),
  ('DEMI_G5.S5.C2', 'DEMI_G5.S5', 'DEMI_G5', false, 2, 'Practical delivery / feasibility', 'Explains a realistic way the solution could be offered, used, or adopted.', 5),
  ('DEMI_G5.S6.C1', 'DEMI_G5.S6', 'DEMI_G5', false, 1, 'Shared teamwork & contribution', 'Roles are balanced and all members visibly contribute to building, testing, or explaining the project.', 5),
  ('DEMI_G5.S6.C2', 'DEMI_G5.S6', 'DEMI_G5', false, 2, 'Technical communication', 'Team explains hardware, code, AI, and design decisions in language appropriate to judges.', 5),
  ('DEMI_G5.S6.C3', 'DEMI_G5.S6', 'DEMI_G5', false, 3, 'Presentation, demo & Q&A', 'Presentation is clear and well paced; demo evidence is convincing; answers show shared understanding.', 5),
  ('DEMI_G5.BONUS.C1', 'DEMI_G5.BONUS', 'DEMI_G5', true, 1, 'Advanced programming feature', 'Optional stronger programming feature (functions, lists, nested logic, etc.) is useful and supported by code/logic evidence.', 5),
  ('DEMI_G5.BONUS.C2', 'DEMI_G5.BONUS', 'DEMI_G5', true, 2, 'Advanced AI feature', 'Optional AI feature goes beyond the basic AI requirement and is supported by a model, screenshot, result, or credible prototype evidence.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DECI Level 1 (DECI_Level_1_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DECI_L1', 'Stage 3 Judges'' Rubric - DECI Level 1', 'MIT App Inventor + Kit Project - Stage 3 Judge Evaluation', 'DECI_Level_1_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 10)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DECI_L1.S1', 'DECI_L1', 1, 'Problem, Research & Solution', 15, false),
  ('DECI_L1.S2', 'DECI_L1', 2, 'System, Circuit & Kit Use', 20, false),
  ('DECI_L1.S3', 'DECI_L1', 3, 'Programming Logic', 20, false),
  ('DECI_L1.S4', 'DECI_L1', 4, 'MIT App Inventor & User Experience', 15, false),
  ('DECI_L1.S5', 'DECI_L1', 5, 'Testing & Integration', 10, false),
  ('DECI_L1.S6', 'DECI_L1', 6, 'Business & Value', 5, false),
  ('DECI_L1.S7', 'DECI_L1', 7, 'Teamwork & Presentation', 15, false),
  ('DECI_L1.BONUS', 'DECI_L1', 8, 'Extra Requirements / Optional Bonus', 10, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DECI_L1.S1.C1', 'DECI_L1.S1', 'DECI_L1', false, 1, 'Problem, target users & research', 'Clearly defines the problem, exact users, importance, and supporting research findings/sources.', 5),
  ('DECI_L1.S1.C2', 'DECI_L1.S1', 'DECI_L1', false, 2, 'Solution & user interaction', 'Solution directly addresses the problem and explains how users will interact with it step by step.', 5),
  ('DECI_L1.S1.C3', 'DECI_L1.S1', 'DECI_L1', false, 3, 'Main features & value', '3-4 main functions are purposeful and connected to the original user need.', 5),
  ('DECI_L1.S2.C1', 'DECI_L1.S2', 'DECI_L1', false, 1, 'System structure', 'Overall system/block flow is clear: trigger/input -> controller/processing -> output/action.', 5),
  ('DECI_L1.S2.C2', 'DECI_L1.S2', 'DECI_L1', false, 2, 'Purposeful kit & component choice', 'Car/Robot Arm Kit and specific components are chosen because they fit the project, not simply because they are available.', 5),
  ('DECI_L1.S2.C3', 'DECI_L1.S2', 'DECI_L1', false, 3, 'Circuit/component understanding', 'Connections and component roles are technically reasonable and match the design.', 5),
  ('DECI_L1.S2.C4', 'DECI_L1.S2', 'DECI_L1', false, 4, 'Best hardware use & integration', 'Hardware capabilities are used effectively and, where implemented, behave reliably as part of the same solution.', 5),
  ('DECI_L1.S3.C1', 'DECI_L1.S3', 'DECI_L1', false, 1, 'Events / inputs', 'Program begins from clear user/system events or inputs and reacts correctly.', 5),
  ('DECI_L1.S3.C2', 'DECI_L1.S3', 'DECI_L1', false, 2, 'Conditions & decisions', 'Decision logic matches the intended behavior and important cases.', 5),
  ('DECI_L1.S3.C3', 'DECI_L1.S3', 'DECI_L1', false, 3, 'Loops / timing / repeated behavior', 'Repeated actions or waiting/timing logic are handled correctly where required.', 5),
  ('DECI_L1.S3.C4', 'DECI_L1.S3', 'DECI_L1', false, 4, 'Outputs & logic consistency', 'Program outputs match the flowchart/blocks and the described system behavior.', 5),
  ('DECI_L1.S4.C1', 'DECI_L1.S4', 'DECI_L1', false, 1, 'App role & user flow', 'App clearly supports or controls the solution and users can navigate the intended flow.', 5),
  ('DECI_L1.S4.C2', 'DECI_L1.S4', 'DECI_L1', false, 2, 'Screens / interface quality', 'Screens are understandable, consistent, and appropriate for the target users.', 5),
  ('DECI_L1.S4.C3', 'DECI_L1.S4', 'DECI_L1', false, 3, 'Blocks & working evidence', 'Real blocks/screens or a working demo show that the planned app logic is implemented.', 5),
  ('DECI_L1.S5.C1', 'DECI_L1.S5', 'DECI_L1', false, 1, 'End-to-end testing evidence', 'Team shows that the app and any hardware interaction were tested through realistic use cases, not only isolated parts.', 5),
  ('DECI_L1.S5.C2', 'DECI_L1.S5', 'DECI_L1', false, 2, 'Reliability & improvement', 'Team identifies failures/limitations and explains changes or next improvements based on testing.', 5),
  ('DECI_L1.S6.C1', 'DECI_L1.S6', 'DECI_L1', false, 1, 'Benefit & delivery model', 'Explains who benefits, the value provided, and a realistic way the solution could reach users.', 5),
  ('DECI_L1.S7.C1', 'DECI_L1.S7', 'DECI_L1', false, 1, 'Shared contribution', 'All team members participate and can explain the part they contributed.', 5),
  ('DECI_L1.S7.C2', 'DECI_L1.S7', 'DECI_L1', false, 2, 'Communication & demonstration', 'Presentation is clear and the live/demo evidence supports the project story.', 5),
  ('DECI_L1.S7.C3', 'DECI_L1.S7', 'DECI_L1', false, 3, 'Q&A & shared understanding', 'Team answers questions accurately and shows shared understanding of app, hardware, logic, and user need.', 5),
  ('DECI_L1.BONUS.C1', 'DECI_L1.BONUS', 'DECI_L1', true, 1, 'AI feature', 'Optional AI/ML/computer vision/NLP feature strengthens the same solution and includes prototype/evidence.', 5),
  ('DECI_L1.BONUS.C2', 'DECI_L1.BONUS', 'DECI_L1', true, 2, 'Advanced App Inventor feature', 'Optional advanced app feature (e.g., multiple screens, data storage, enhanced interaction) is useful and supported by working evidence.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DECI Level 2 (DECI_Level_2_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DECI_L2', 'Stage 3 Judges'' Rubric - DECI Level 2', 'Arduino + Web Integration Project - Stage 3 Judge Evaluation', 'DECI_Level_2_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 10)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DECI_L2.S1', 'DECI_L2', 1, 'Problem, Research & Solution', 15, false),
  ('DECI_L2.S2', 'DECI_L2', 2, 'System, Circuit, Hardware & Kit', 25, false),
  ('DECI_L2.S3', 'DECI_L2', 3, 'Programming & Control Logic', 15, false),
  ('DECI_L2.S4', 'DECI_L2', 4, 'Web Interface Integration', 15, false),
  ('DECI_L2.S5', 'DECI_L2', 5, 'Testing & Hardware Evidence', 10, false),
  ('DECI_L2.S6', 'DECI_L2', 6, 'Business & Value', 5, false),
  ('DECI_L2.S7', 'DECI_L2', 7, 'Teamwork & Presentation', 15, false),
  ('DECI_L2.BONUS', 'DECI_L2', 8, 'Extra Requirements / Optional Bonus', 10, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DECI_L2.S1.C1', 'DECI_L2.S1', 'DECI_L2', false, 1, 'Problem, users & research', 'Defines a real problem and target users with relevant research findings/references.', 5),
  ('DECI_L2.S1.C2', 'DECI_L2.S1', 'DECI_L2', false, 2, 'Solution fit & user interaction', 'Solution directly addresses the problem and clearly explains how users interact with it.', 5),
  ('DECI_L2.S1.C3', 'DECI_L2.S1', 'DECI_L2', false, 3, 'Features & value', 'Main functions are purposeful, coherent, and create a clear advantage or value for the user.', 5),
  ('DECI_L2.S2.C1', 'DECI_L2.S2', 'DECI_L2', false, 1, 'System data flow', 'Full path from sensor/input -> Arduino processing -> communication/output -> web/software is clear and correct.', 5),
  ('DECI_L2.S2.C2', 'DECI_L2.S2', 'DECI_L2', false, 2, 'Purposeful kit selection', 'Car/Robot Arm Kit choice is justified by the components actually needed; unnecessary kit parts are not forced into the project.', 5),
  ('DECI_L2.S2.C3', 'DECI_L2.S2', 'DECI_L2', false, 3, 'Component roles', 'Arduino, sensors, actuators, communication modules, and other parts each have a clear and correct role.', 5),
  ('DECI_L2.S2.C4', 'DECI_L2.S2', 'DECI_L2', false, 4, 'Circuit correctness', 'Power, ground, signal, TX/RX, and other relevant connections are technically reasonable and match the prototype.', 5),
  ('DECI_L2.S2.C5', 'DECI_L2.S2', 'DECI_L2', false, 5, 'Best hardware use & reliability', 'Hardware is used effectively for the problem and performs consistently in repeated trials/demos.', 5),
  ('DECI_L2.S3.C1', 'DECI_L2.S3', 'DECI_L2', false, 1, 'Inputs, conditions & outputs', 'Sensor/input readings drive correct decisions and outputs.', 5),
  ('DECI_L2.S3.C2', 'DECI_L2.S3', 'DECI_L2', false, 2, 'Loops & functions', 'Repeated behavior and reusable functions/blocks are used appropriately and clearly.', 5),
  ('DECI_L2.S3.C3', 'DECI_L2.S3', 'DECI_L2', false, 3, 'Control reliability', 'Program behavior is stable, understandable, and consistent with the flowchart/pseudocode.', 5),
  ('DECI_L2.S4.C1', 'DECI_L2.S4', 'DECI_L2', false, 1, 'Web role & system connection', 'Web interface displays/controls the exact information produced by the system and has a clear purpose.', 5),
  ('DECI_L2.S4.C2', 'DECI_L2.S4', 'DECI_L2', false, 2, 'UI quality & usability', 'Interface is readable, organized, and appropriate for the target users.', 5),
  ('DECI_L2.S4.C3', 'DECI_L2.S4', 'DECI_L2', false, 3, 'Working integration evidence', 'Screenshots/demo show that the web interface and hardware/data flow are credibly connected or implemented.', 5),
  ('DECI_L2.S5.C1', 'DECI_L2.S5', 'DECI_L2', false, 1, 'Evidence of testing', 'Shows repeated hardware/software tests, measurements, logs, screenshots, or scenario results.', 5),
  ('DECI_L2.S5.C2', 'DECI_L2.S5', 'DECI_L2', false, 2, 'Improvement & robustness', 'Team uses findings to improve thresholds, communication, UI, wiring, reliability, or error handling.', 5),
  ('DECI_L2.S6.C1', 'DECI_L2.S6', 'DECI_L2', false, 1, 'Customer, alternatives & value', 'Identifies customer, existing alternatives/competitors, and explains practical value/differentiation.', 5),
  ('DECI_L2.S7.C1', 'DECI_L2.S7', 'DECI_L2', false, 1, 'Shared contribution & roles', 'Team members visibly contribute across hardware, code, web, testing, or documentation.', 5),
  ('DECI_L2.S7.C2', 'DECI_L2.S7', 'DECI_L2', false, 2, 'Technical communication', 'Explains system flow and design decisions clearly without relying on one member for all technical answers.', 5),
  ('DECI_L2.S7.C3', 'DECI_L2.S7', 'DECI_L2', false, 3, 'Presentation, demo & Q&A', 'Presentation is clear, well paced, evidence-based, and questions are answered confidently.', 5),
  ('DECI_L2.BONUS.C1', 'DECI_L2.BONUS', 'DECI_L2', true, 1, 'AI / data feature', 'Optional AI, ML, or data-analysis feature uses relevant project data and includes a useful result or visualization.', 5),
  ('DECI_L2.BONUS.C2', 'DECI_L2.BONUS', 'DECI_L2', true, 2, 'Advanced system feature', 'Optional cybersecurity, automation, IoT, or software enhancement strengthens the existing system and includes evidence.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DECI Level 3 (DECI_Level_3_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DECI_L3', 'Stage 3 Judges'' Rubric - DECI Level 3', 'ESP32 + Track Integration Project - Stage 3 Judge Evaluation', 'DECI_Level_3_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 10)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DECI_L3.S1', 'DECI_L3', 1, 'Problem, Research & Solution', 15, false),
  ('DECI_L3.S2', 'DECI_L3', 2, 'System, Hardware, IoT & Circuit', 25, false),
  ('DECI_L3.S3', 'DECI_L3', 3, 'Programming & AI / Data', 20, false),
  ('DECI_L3.S4', 'DECI_L3', 4, 'Digital Identity & Track Integration', 10, false),
  ('DECI_L3.S5', 'DECI_L3', 5, 'Testing & Validation', 10, false),
  ('DECI_L3.S6', 'DECI_L3', 6, 'Business & Value', 5, false),
  ('DECI_L3.S7', 'DECI_L3', 7, 'Teamwork & Presentation', 15, false),
  ('DECI_L3.BONUS', 'DECI_L3', 8, 'Extra Requirements / Optional Bonus', 10, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DECI_L3.S1.C1', 'DECI_L3.S1', 'DECI_L3', false, 1, 'Problem, user & research', 'Clearly defines the problem/user and supports it with relevant research findings and references.', 5),
  ('DECI_L3.S1.C2', 'DECI_L3.S1', 'DECI_L3', false, 2, 'Solution & user interaction', 'Solution directly addresses the problem and explains a complete user interaction.', 5),
  ('DECI_L3.S1.C3', 'DECI_L3.S1', 'DECI_L3', false, 3, 'Features & value', 'Main functions are coherent, useful, and consistent with the same target user.', 5),
  ('DECI_L3.S2.C1', 'DECI_L3.S2', 'DECI_L3', false, 1, 'ESP32 system architecture', 'System clearly explains sensor/input -> ESP32 processing -> decision -> output/communication, including relevant ESP32 capabilities.', 5),
  ('DECI_L3.S2.C2', 'DECI_L3.S2', 'DECI_L3', false, 2, 'Purposeful platform & component choice', 'Kit/platform, ESP32/ESP32 Camera, sensors, and actuators are selected because they fit the project.', 5),
  ('DECI_L3.S2.C3', 'DECI_L3.S2', 'DECI_L3', false, 3, 'IoT communication', 'Wi-Fi/Bluetooth/data flow is technically sensible, including two-way communication where needed.', 5),
  ('DECI_L3.S2.C4', 'DECI_L3.S2', 'DECI_L3', false, 4, 'Circuit correctness', 'Circuit connections and selected GPIO/input types are reasonable and match the implemented plan.', 5),
  ('DECI_L3.S2.C5', 'DECI_L3.S2', 'DECI_L3', false, 5, 'Best hardware use & reliability', 'Hardware/ESP32 capabilities are used effectively and operate consistently under repeated demonstrations.', 5),
  ('DECI_L3.S3.C1', 'DECI_L3.S3', 'DECI_L3', false, 1, 'Programming/control logic', 'Inputs, decisions, timing/loops, outputs, and communication are implemented logically and reliably.', 5),
  ('DECI_L3.S3.C2', 'DECI_L3.S3', 'DECI_L3', false, 2, 'Data collection & decisions', 'Collected sensor/image data is relevant and is used appropriately to drive decisions or actions.', 5),
  ('DECI_L3.S3.C3', 'DECI_L3.S3', 'DECI_L3', false, 3, 'AI approach & relevance', 'If AI/computer vision is used, classification/object detection or other approach fits the problem and data.', 5),
  ('DECI_L3.S3.C4', 'DECI_L3.S3', 'DECI_L3', false, 4, 'Evidence of AI/data flow', 'Shows model/data-flow/visual evidence and explains how results connect back to the system.', 5),
  ('DECI_L3.S4.C1', 'DECI_L3.S4', 'DECI_L3', false, 1, 'Digital identity', 'Project name, logo, palette, and visual style are consistent and fit the product/user.', 5),
  ('DECI_L3.S4.C2', 'DECI_L3.S4', 'DECI_L3', false, 2, 'Applied track integration', 'Relevant team track output (Web, UI/UX, Data Science, Cybersecurity) is clearly connected to the same ESP32 project and shows real evidence.', 5),
  ('DECI_L3.S5.C1', 'DECI_L3.S5', 'DECI_L3', false, 1, 'Testing evidence & success checks', 'Shows repeated functional tests or data/communication tests with observable success criteria.', 5),
  ('DECI_L3.S5.C2', 'DECI_L3.S5', 'DECI_L3', false, 2, 'Improvement & system reliability', 'Team identifies weaknesses and improves hardware, logic, data, interface, or communication based on evidence.', 5),
  ('DECI_L3.S6.C1', 'DECI_L3.S6', 'DECI_L3', false, 1, 'Customer, value & pricing', 'Target customer, value proposition, and basic pricing/delivery idea are clear and realistic.', 5),
  ('DECI_L3.S7.C1', 'DECI_L3.S7', 'DECI_L3', false, 1, 'Cross-track teamwork', 'Members integrate their track contributions into one solution instead of presenting disconnected pieces.', 5),
  ('DECI_L3.S7.C2', 'DECI_L3.S7', 'DECI_L3', false, 2, 'Communication & technical ownership', 'Different members can explain decisions and demonstrate understanding beyond only their own slide/part.', 5),
  ('DECI_L3.S7.C3', 'DECI_L3.S7', 'DECI_L3', false, 3, 'Presentation, demo & Q&A', 'Project story is clear and professional; evidence is well selected; team handles judge questions effectively.', 5),
  ('DECI_L3.BONUS.C1', 'DECI_L3.BONUS', 'DECI_L3', true, 1, 'Advanced AI feature', 'Optional advanced AI/ML feature goes beyond the core data plan and includes prototype/evidence.', 5),
  ('DECI_L3.BONUS.C2', 'DECI_L3.BONUS', 'DECI_L3', true, 2, 'Advanced system feature', 'Optional stronger IoT, cybersecurity, data processing, or digital experience feature improves the same system and includes evidence.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

-- ---- Stage 3 Judges' Rubric - DECI Levels 4 & 5 (DECI_Levels_4_5_Judges_Rubric_Revised.pdf)
insert into public.rubric_templates (id, title, subtitle, source_pdf, scale_instruction, guidance, core_max, bonus_max) values
  ('DECI_L45', 'Stage 3 Judges'' Rubric - DECI Levels 4 & 5', 'Combined Advanced Project - Stage 3 Judge Evaluation', 'DECI_Levels_4_5_Judges_Rubric_Revised.pdf', 'Enter ONE number from 1 to 5. Every row is worth 5 points; harder sections have more rows and therefore more weight.', 'Judge the final Stage 3 work, using the previous-phase requirements as the baseline. Reward evidence, correct integration, and purposeful design - not complexity for its own sake. Testing: look for real trials/results, not only claims. Hardware: reward the best-fit use of components and reliable integration. Teamwork & presentation: look for shared ownership, clear communication, and the ability of multiple members to answer questions.', 100, 15)
on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, source_pdf = excluded.source_pdf,
  scale_instruction = excluded.scale_instruction, guidance = excluded.guidance, core_max = excluded.core_max, bonus_max = excluded.bonus_max;
insert into public.rubric_sections (id, template_id, position, title, weight, is_bonus) values
  ('DECI_L45.S1', 'DECI_L45', 1, 'Problem Analysis & Complete Solution', 10, false),
  ('DECI_L45.S2', 'DECI_L45', 2, 'Architecture, Hardware & Embedded IoT', 25, false),
  ('DECI_L45.S3', 'DECI_L45', 3, 'AI, Data Processing & Data Science', 20, false),
  ('DECI_L45.S4', 'DECI_L45', 4, 'Product, UX, Web & Cybersecurity', 15, false),
  ('DECI_L45.S5', 'DECI_L45', 5, 'Business, Testing & Improvement', 15, false),
  ('DECI_L45.S6', 'DECI_L45', 6, 'Teamwork & Presentation', 15, false),
  ('DECI_L45.BONUS', 'DECI_L45', 7, 'Extra Requirements / Optional Bonus', 15, true)
on conflict (id) do update set position = excluded.position, title = excluded.title, weight = excluded.weight, is_bonus = excluded.is_bonus;
insert into public.rubric_criteria (id, section_id, template_id, is_bonus, position, title, description, max_points) values
  ('DECI_L45.S1.C1', 'DECI_L45.S1', 'DECI_L45', false, 1, 'Problem, research & opportunity', 'Defines the real problem, target users, existing alternatives, supporting research, and the specific value/opportunity for the solution.', 5),
  ('DECI_L45.S1.C2', 'DECI_L45.S1', 'DECI_L45', false, 2, 'Complete end-to-end solution', 'User journey and system behavior form a complete flow from data capture/input through processing, user action, and feedback/logging where appropriate.', 5),
  ('DECI_L45.S2.C1', 'DECI_L45.S2', 'DECI_L45', false, 1, 'System architecture & data flow', 'Hardware, ESP32/ESP32 Camera, communication, AI/software processing, and user interface are connected in a technically coherent architecture.', 5),
  ('DECI_L45.S2.C2', 'DECI_L45.S2', 'DECI_L45', false, 2, 'Purposeful hardware selection', 'Physical platform, sensors/actuators, ESP32, and ESP32 Camera roles are justified by the problem; components are not added without purpose.', 5),
  ('DECI_L45.S2.C3', 'DECI_L45.S2', 'DECI_L45', false, 3, 'Circuit & embedded logic', 'Circuit, input processing, states/events, actuator responses, and control logic are technically sound and match the implementation.', 5),
  ('DECI_L45.S2.C4', 'DECI_L45.S2', 'DECI_L45', false, 4, 'IoT / communication integration', 'Data transmission, cloud/local processing, and device-to-system communication are reliable and appropriate for the use case.', 5),
  ('DECI_L45.S2.C5', 'DECI_L45.S2', 'DECI_L45', false, 5, 'Best hardware use, reliability & scalability', 'Hardware capabilities are used efficiently; system performs consistently and design choices consider reliability and practical scaling.', 5),
  ('DECI_L45.S3.C1', 'DECI_L45.S3', 'DECI_L45', false, 1, 'Data pipeline', 'Data collection, preparation, processing, and decision flow are clear and technically appropriate.', 5),
  ('DECI_L45.S3.C2', 'DECI_L45.S3', 'DECI_L45', false, 2, 'AI/ML approach & performance evidence', 'Chosen AI/ML method fits the task; team shows relevant outputs, confidence/accuracy evidence, or justified evaluation.', 5),
  ('DECI_L45.S3.C3', 'DECI_L45.S3', 'DECI_L45', false, 3, 'Data science insight', 'Collected project data is organized/visualized to produce a useful insight that supports a real user or business decision.', 5),
  ('DECI_L45.S3.C4', 'DECI_L45.S3', 'DECI_L45', false, 4, 'Integration of AI/data into system behavior', 'AI/data results trigger meaningful dashboard updates, alerts, predictions, recommendations, or other actions in the same solution.', 5),
  ('DECI_L45.S4.C1', 'DECI_L45.S4', 'DECI_L45', false, 1, 'Product identity & professional visualization', 'Brand/UI is consistent and polished; mixed Level 4-5 team includes strong product visuals/digital assets appropriate to Level 5 depth.', 5),
  ('DECI_L45.S4.C2', 'DECI_L45.S4', 'DECI_L45', false, 2, 'Web application integration', 'Web/app interface exposes the correct live/history/control information from the hardware/AI system and supports the intended user flow.', 5),
  ('DECI_L45.S4.C3', 'DECI_L45.S4', 'DECI_L45', false, 3, 'Cybersecurity design', 'Authentication/authorization, access control, communication/data protection, and relevant risks are addressed in a way that fits the architecture.', 5),
  ('DECI_L45.S5.C1', 'DECI_L45.S5', 'DECI_L45', false, 1, 'Business model & product planning', 'Customer, value proposition, pricing, competitors/alternatives, and delivery approach are complete and realistic.', 5),
  ('DECI_L45.S5.C2', 'DECI_L45.S5', 'DECI_L45', false, 2, 'Testing evidence & measurable success criteria', 'Team tests under relevant conditions and shows evidence such as logs, accuracy results, repeated runs, failure cases, or comparison to ground truth.', 5),
  ('DECI_L45.S5.C3', 'DECI_L45.S5', 'DECI_L45', false, 3, 'Iteration, reliability & improvement', 'Test results lead to concrete improvements; team can explain limitations, reliability concerns, and next technical/product steps.', 5),
  ('DECI_L45.S6.C1', 'DECI_L45.S6', 'DECI_L45', false, 1, 'Cross-discipline teamwork & ownership', 'Hardware, software, AI/data, design, security, and business work are integrated; members have visible contributions and shared ownership.', 5),
  ('DECI_L45.S6.C2', 'DECI_L45.S6', 'DECI_L45', false, 2, 'Technical communication & decision justification', 'Team explains architecture and tradeoffs clearly and can justify why technologies/components were chosen.', 5),
  ('DECI_L45.S6.C3', 'DECI_L45.S6', 'DECI_L45', false, 3, 'Presentation, live demo & Q&A', 'Presentation is polished and concise, demo evidence is convincing, and multiple members answer judge questions confidently.', 5),
  ('DECI_L45.BONUS.C1', 'DECI_L45.BONUS', 'DECI_L45', true, 1, 'Advanced AI/ML feature', 'Optional advanced AI feature goes beyond the core AI/data pipeline and is supported by evidence or a credible prototype.', 5),
  ('DECI_L45.BONUS.C2', 'DECI_L45.BONUS', 'DECI_L45', true, 2, 'Advanced IoT / security feature', 'Optional advanced cloud, real-time communication, automation, monitoring, or security capability strengthens the same architecture.', 5),
  ('DECI_L45.BONUS.C3', 'DECI_L45.BONUS', 'DECI_L45', true, 3, 'Level 5 advanced security / reliability', 'Optional Level-5-depth feature such as stronger authentication, secure protocols, monitoring, risk management, or reliability safeguards is demonstrated with evidence.', 5)
on conflict (id) do update set position = excluded.position, title = excluded.title, description = excluded.description;

insert into public.competitions (code, organization, label, template_id, sort_order) values
  ('DEMI_G4', 'DEMI', 'Grade 4', 'DEMI_G4', 1),
  ('DEMI_G5', 'DEMI', 'Grade 5', 'DEMI_G5', 2),
  ('DECI_L1', 'DECI', 'Level 1', 'DECI_L1', 3),
  ('DECI_L2', 'DECI', 'Level 2', 'DECI_L2', 4),
  ('DECI_L3', 'DECI', 'Level 3', 'DECI_L3', 5),
  ('DECI_L45', 'DECI', 'Levels 4 & 5', 'DECI_L45', 6)
on conflict (code) do update set organization = excluded.organization, label = excluded.label, template_id = excluded.template_id, sort_order = excluded.sort_order;

insert into public.levels (code, organization, label, competition_code, sort_order) values
  ('G4', 'DEMI', 'Grade 4', 'DEMI_G4', 1),
  ('G5', 'DEMI', 'Grade 5', 'DEMI_G5', 2),
  ('L1', 'DECI', 'Level 1', 'DECI_L1', 3),
  ('L2', 'DECI', 'Level 2', 'DECI_L2', 4),
  ('L3', 'DECI', 'Level 3', 'DECI_L3', 5),
  ('L4', 'DECI', 'Level 4', 'DECI_L45', 6),
  ('L5', 'DECI', 'Level 5', 'DECI_L45', 7)
on conflict (code) do update set organization = excluded.organization, label = excluded.label, competition_code = excluded.competition_code, sort_order = excluded.sort_order;

insert into public.results_signal (competition_code) select code from public.competitions on conflict do nothing;

-- Integrity check: every section weight = rows x 5, core sections sum to core_max,
-- bonus section weight = bonus_max. Fails the migration if the seed is inconsistent.
do $$
declare bad text;
begin
  select string_agg(s.id, ', ') into bad
  from public.rubric_sections s
  where s.weight <> (select count(*) * 5 from public.rubric_criteria c where c.section_id = s.id);
  if bad is not null then raise exception 'Section weight mismatch: %', bad; end if;

  select string_agg(t.id, ', ') into bad
  from public.rubric_templates t
  where t.core_max <> (select coalesce(sum(weight), 0) from public.rubric_sections where template_id = t.id and not is_bonus)
     or t.bonus_max <> (select coalesce(sum(weight), 0) from public.rubric_sections where template_id = t.id and is_bonus);
  if bad is not null then raise exception 'Template total mismatch: %', bad; end if;
end;
$$;
