import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, ChevronRight, Clock3, ListChecks, RefreshCw, Search, Users } from 'lucide-react';
import { fetchAdminPage, fetchAdminProgressStats, loadReference, subscribeToResults, type AdminProgressStats, type JudgeAssignmentPageRow, type Reference } from '@/lib/api';
import { errorMessage } from '@/lib/supabase';
import type { Profile } from '@/lib/types';
import Pagination from '@/components/Pagination';
import { Alert, Badge, Button, Card, EmptyState, Input, Modal, OrgBadge, PageHeader, ProgressBar, Select, Spinner, StatCard, formatDate } from '@/components/ui';

interface ProgressRow { id:string;email:string;full_name:string;organizations:string[];assigned:number;completed:number;in_progress:number;not_started:number;completion_percentage:number }
interface JudgeChoice extends Profile { assigned:number;submitted:number;drafts:number }
const statusOf=(row:JudgeAssignmentPageRow)=>!row.evaluation_id?'not_started':row.evaluation_status==='submitted'?'submitted':'in_progress';
const label={not_started:'Not Started',in_progress:'In Progress',submitted:'Submitted'} as const;

export default function JudgeProgressPage(){
  const[reference,setReference]=useState<Reference|null>(null),[rows,setRows]=useState<ProgressRow[]>([]),[judges,setJudges]=useState<JudgeChoice[]>([]),[error,setError]=useState<string|null>(null);
  const[stats,setStats]=useState<AdminProgressStats>({judges_not_started:0,judges_incomplete:0,judges_finished:0,teams_waiting:0});
  const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20);
  const[search,setSearch]=useState(''),[organization,setOrganization]=useState(''),[level,setLevel]=useState(''),[governorate,setGovernorate]=useState(''),[judge,setJudge]=useState(''),[status,setStatus]=useState('');
  const[selected,setSelected]=useState<ProgressRow|null>(null),[detailRows,setDetailRows]=useState<JudgeAssignmentPageRow[]>([]),[detailTotal,setDetailTotal]=useState(0),[detailPage,setDetailPage]=useState(1),[detailPageSize,setDetailPageSize]=useState(20);
  const filters={search,organization,level,governorate,judge,status};
  const load=useCallback(async(quiet=false)=>{quiet?setRefreshing(true):setLoading(true);try{const[ref,result,judgePage,nextStats]=await Promise.all([loadReference(true),fetchAdminPage<ProgressRow>('progress',filters,page,pageSize),fetchAdminPage<JudgeChoice>('judges',{status:'all'},1,100),fetchAdminProgressStats()]);setReference(ref);setRows(result.rows);setTotal(result.total);setJudges(judgePage.rows.filter(x=>x.role==='judge'));setStats(nextStats);setError(null)}catch(e){setError(errorMessage(e))}finally{setLoading(false);setRefreshing(false)}},[search,organization,level,governorate,judge,status,page,pageSize]);
  const loadDetails=useCallback(async()=>{if(!selected)return;try{const result=await fetchAdminPage<JudgeAssignmentPageRow>('progress_details',{...filters,judge:selected.id},detailPage,detailPageSize);setDetailRows(result.rows);setDetailTotal(result.total)}catch(e){setError(errorMessage(e))}},[selected,search,organization,level,governorate,status,detailPage,detailPageSize]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>clearTimeout(timer)},[load,search]);
  useEffect(()=>{void loadDetails()},[loadDetails]);
  useEffect(()=>subscribeToResults(()=>{void load(true);void loadDetails()}),[load,loadDetails]);
  const change=(setter:(v:string)=>void,value:string)=>{setter(value);setPage(1);setDetailPage(1)};
  if(loading&&!reference)return <Spinner label="Loading judge progress…"/>;
  if(!reference)return <Alert tone="error">{error}</Alert>;
  return <div><PageHeader title="Judge Progress" subtitle="Current assignment status derived from evaluations." actions={<Button variant="secondary" loading={refreshing} onClick={()=>void load(true)}><RefreshCw size={16}/>Refresh</Button>}/>{error&&<Alert tone="error" className="mb-4">{error}</Alert>}
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Not started" value={stats.judges_not_started} icon={<Clock3 size={20}/>} tone="slate" hint="Judges with no started assignments"/><StatCard label="Incomplete judges" value={stats.judges_incomplete} icon={<Users size={20}/>} tone="amber" hint="At least one assignment outstanding"/><StatCard label="Finished judges" value={stats.judges_finished} icon={<CheckCircle2 size={20}/>} tone="green" hint="All assigned evaluations submitted"/><StatCard label="Teams waiting" value={stats.teams_waiting} icon={<ListChecks size={20}/>} tone="red" hint="Waiting for one or more judges"/></div>
    <Card className="mb-4 p-3"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-6"><div className="relative md:col-span-2"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input className="pl-8" placeholder="Judge name, Team ID or team name" value={search} onChange={e=>change(setSearch,e.target.value)}/></div><Select value={organization} onChange={e=>{change(setOrganization,e.target.value);setLevel('')}}><option value="">All organizations</option><option>DEMI</option><option>DECI</option></Select><Select value={level} onChange={e=>change(setLevel,e.target.value)}><option value="">All grades / levels</option>{reference.levels.filter(x=>!organization||x.organization===organization).map(x=><option key={x.code} value={x.code}>{x.organization} · {x.label}</option>)}</Select><Select value={governorate} onChange={e=>change(setGovernorate,e.target.value)}><option value="">All governorates</option>{reference.governorates.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</Select><Select value={status} onChange={e=>change(setStatus,e.target.value)}><option value="">Any status</option><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="submitted">Submitted</option></Select><Select className="md:col-span-2" value={judge} onChange={e=>change(setJudge,e.target.value)}><option value="">All judges</option>{judges.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</Select></div></Card>
    <Card className="overflow-hidden">{rows.length===0?<EmptyState icon={<Users/>} title="No judges match these filters"/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="bg-slate-50 text-left text-xs uppercase text-slate-500"><th className="px-5 py-3">Judge</th><th className="px-3 py-3">Organizations</th><th className="px-3 py-3">Assigned</th><th className="px-3 py-3">Completed</th><th className="px-3 py-3">In progress</th><th className="px-3 py-3">Not started</th><th className="px-3 py-3">Progress</th><th/></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="px-5 py-3"><button className="font-semibold text-brand-700" onClick={()=>{setSelected(row);setDetailPage(1)}}>{row.full_name||row.email}</button><span className="block text-xs text-slate-500">{row.email}</span></td><td className="px-3 py-3"><div className="flex gap-1">{row.organizations.map(org=><OrgBadge key={org} org={org as 'DEMI'|'DECI'}/>)}</div></td><td className="px-3 py-3">{row.assigned}</td><td className="px-3 py-3 text-emerald-700">{row.completed}</td><td className="px-3 py-3 text-amber-700">{row.in_progress}</td><td className="px-3 py-3">{row.not_started}</td><td className="min-w-40 px-3 py-3"><span className="text-xs">{row.completion_percentage}%</span><ProgressBar value={row.completed} max={row.assigned}/></td><td><button onClick={()=>setSelected(row)}><ChevronRight/></button></td></tr>)}</tbody></table></div>}<Pagination page={page} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/></Card>
    <Modal open={!!selected} onClose={()=>setSelected(null)} title={`Assigned teams · ${selected?.full_name||selected?.email||''}`} size="xl">{detailRows.length===0?<EmptyState title="No assigned teams in this view"/>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="bg-slate-50 text-left text-xs uppercase text-slate-500"><th className="px-3 py-2">Team ID</th><th className="px-3 py-2">Team / project</th><th className="px-3 py-2">Organization</th><th className="px-3 py-2">Grade / level</th><th className="px-3 py-2">Governorate</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Last activity</th><th className="px-3 py-2">Submitted</th></tr></thead><tbody className="divide-y">{detailRows.map(row=>{const s=statusOf(row);return <tr key={row.id}><td className="px-3 py-2 font-semibold">{row.team_code}</td><td className="px-3 py-2">{row.name}<span className="block text-xs text-slate-500">{row.project_name}</span></td><td className="px-3 py-2"><OrgBadge org={row.organization}/></td><td className="px-3 py-2">{row.level_label}</td><td className="px-3 py-2">{row.governorate_name}</td><td className="px-3 py-2"><Badge tone={s==='submitted'?'green':s==='in_progress'?'amber':'slate'}>{label[s]}</Badge></td><td className="px-3 py-2">{formatDate(row.evaluation_updated_at)}</td><td className="px-3 py-2">{formatDate(row.submitted_at)}</td></tr>})}</tbody></table></div>}<Pagination page={detailPage} pageSize={detailPageSize} total={detailTotal} onPageChange={setDetailPage} onPageSizeChange={size=>{setDetailPageSize(size);setDetailPage(1)}}/></Modal>
  </div>;
}
